const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Deploying DePoker2 contract...");

  const DePoker2 = await hre.ethers.getContractFactory("DePoker2");
  const depoker2 = await DePoker2.deploy();

  await depoker2.waitForDeployment();

  const contractAddress = await depoker2.getAddress();
  console.log("DePoker2 deployed to:", contractAddress);

  // Save deployment info
  const deploymentInfo = {
    address: contractAddress,
    network: hre.network.name,
    chainId: hre.network.config.chainId,
    deployedAt: new Date().toISOString()
  };

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir, { recursive: true });
  }

  const deploymentPath = path.join(deploymentsDir, `localhost-DePoker2.json`);
  fs.writeFileSync(deploymentPath, JSON.stringify(deploymentInfo, null, 2));
  console.log("Saved deployment info to", deploymentPath);

  // Update blockchain config
  const configPath = path.join(__dirname, "..", "blockchain", "config", "contract.ts");
  const configContent = `// Auto-generated by deployment script
import DePoker2Artifact from '../abi/DePoker2.json';

export const contractAddress = '${contractAddress}';
export const rpcUrl = 'http://127.0.0.1:8545';
export const chainId = 31337;

export const HARDHAT_NETWORK = {
  rpcUrl,
  chainId,
};

export const DEPOKER2_CONTRACT = {
  address: contractAddress,
  abi: DePoker2Artifact.abi,
};
`;
  
  fs.writeFileSync(configPath, configContent);
  console.log("✅ Updated blockchain/config/contract.ts");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
