// Auto-generated by deployment script
import DePoker2Artifact from '../abi/DePoker2.json';

export const contractAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3';
export const rpcUrl = 'http://127.0.0.1:8545';
export const chainId = 31337;

export const HARDHAT_NETWORK = {
  rpcUrl,
  chainId,
};

export const DEPOKER2_CONTRACT = {
  address: contractAddress,
  abi: DePoker2Artifact.abi,
};
